In [3]:
import numpy as np

In [8]:
matrix1 = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [9]:
matrix1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [10]:
matrix2 = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [11]:
# operations in matrix add , substract  , multiply , dot product , inverse , transpse

In [13]:
matrix1 + matrix2

matrix([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [14]:
np.add(matrix1 , matrix2)

matrix([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [15]:
matrix1 - matrix2

matrix([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [16]:
np.subtract(matrix1 , matrix2)

matrix([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [20]:
np.dot(matrix1 , matrix2)
#dot product of matrix1 and matrix2

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [19]:
np.multiply(matrix1 , matrix2) # element wise multiplication

matrix([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])